name: es_compression
description: Compression framework providing FFI implementations for Brotli, Lz4, Zstd (Zstandard) with ready-to-use prebuilt binaries for Win/Linux/Mac.
version: 2.0.8
homepage: https://www.instantiations.com
issue_tracker: https://github.com/instantiations/es_compression/issues
repository: https://github.com/instantiations/es_compression

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  escompress: es_compress

dependencies:
  args: ^2.0.0
  ffi: '>=1.0.0 <3.0.0'
  stack_trace: ^1.10.0
  stream_channel: ^2.1.0

dev_dependencies:
  benchmark_harness: ^2.0.0
  collection: ^1.15.0
  lints: ^1.0.1
  test: ^1.16.0
