name: es_compression
description: A port of the unified compression framework from the VAST Platform (VA Smalltalk)
version: 0.1.0
homepage: https://www.instantiations.com

environment:
  sdk: '>=2.7.0 <3.0.0'

executables:
  escompress: es_compress.dart

dependencies:
  ffi: ^0.1.3

dev_dependencies:
  benchmark_harness: ^1.0.4
  effective_dart: ^1.2.4
  pedantic: ^1.8.0
  test: ^1.6.0
