name: Test

on: push
#  push:
#    branches: [main]
#  pull_request:
#    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Test latest stable, beta, dev, and main channels
        sdk: [stable, beta, dev, main]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          sdk: ${{ matrix.sdk }}
      - run: pub get
      - name: Run tests
        run: |
          echo "main() { print('hello world'); }" > hello.dart
          dart hello.dart